// 00_Work/meadia_system/src/App.vue
<template>
  <div id="app">
    <router-view />
  </div>
</template>

<script>
export default {
  name: "app",
  created() {
    if (sessionStorage.getItem("store")) {
      this.$store.replaceState(
        Object.assign(
          {},
          this.$store.state,
          JSON.parse(sessionStorage.getItem("store"))
        )
      );
    }
    window.addEventListener("beforeunload", () => {
      sessionStorage.setItem("store", JSON.stringify(this.$store.state));
    });
  }
};
</script>

<style>
@import "assets/css/base.css";
</style>

// 26_react/09_hooks/learn-hooks/src/03_自定义hook/05_数据存储的localStorage/App.js
import { useState, useEffect } from 'react'

function useLocalStorage(key) {
  const [data, setData] = useState(() => JSON.parse(window.localStorage.getItem(key)))

  useEffect(() => {
    window.localStorage.setItem(key, JSON.stringify(data))
  }, [data])

  return [data, setData]
}

function Home() {
  const [name, setName] = useLocalStorage('name')

  return (
    <div>
      <h2>Home</h2>
      <h2>name: {name}</h2>
      <button onClick={e => setName('codewhy')}>存储name</button>
    </div>
  )
}

export default function App() {

  return (
    <div>
      <Home/>
    </div>
  )
}
